import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Provider from './Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={`${inter.className} bg-gray-50 dark:bg-neutral-800 text-black dark:text-white w-screen h-screen`}>
      {/* <body> */}
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
